name:          SV Code Guide
description:   Standards for developing flexible, durable, and sustainable HTML, CSS and JavaScript.
url:           https://simpleviewinc.github.io/code-guide

markdown:      rdiscount
permalink:     pretty
pygments:      true
